name: ${ETCD_PROJECT_NAME:-shared-etcd}

networks:
  internal:
    name: ${ETCD_NETWORK:-shared_etcd}
    external: true

services:
  etcd:
    image: ${ETCD_IMAGE:-registry.k8s.io/etcd:3.5.21-0}
    restart: unless-stopped
    env_file:
      - ./.env.etcd
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "3"
    command:
      - /usr/local/bin/etcd
      - --data-dir=/etcd-data
      - --name=${ETCD_NODE_NAME:-node1}
      - --initial-advertise-peer-urls=http://etcd:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://etcd:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-cluster=${ETCD_NODE_NAME:-node1}=http://etcd:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=${ETCD_CLUSTER_TOKEN:-etcd-cluster-1}
    environment:
      ETCDCTL_API: "3"
    volumes:
      - ${HOST_ETCD_DATA_DIR:-/data/etcd}:/etcd-data
    ports:
      - "127.0.0.1:${ETCD_CLIENT_PORT:-2379}:2379"
      - "127.0.0.1:${ETCD_PEER_PORT:-2380}:2380"
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      internal:
        aliases:
          - etcd
