name: ${PROXY_PROJECT_NAME:-shared-proxy}

networks:
  internal:
    name: ${PROXY_NETWORK:-shared_proxy}
    external: true

services:
  nginx:
    image: ${NGINX_IMAGE:-nginx:latest}
    restart: unless-stopped
    env_file:
      - ./.env.proxy
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./templates-enabled:/etc/nginx/templates:ro
      - /data/certbot-www:/var/www/certbot:ro
      - /data/letsencrypt:/etc/letsencrypt:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - internal

  certbot:
    image: ${CERTBOT_IMAGE:-certbot/certbot:v2.11.0}
    env_file:
      - ./.env.proxy
    volumes:
      - /data/certbot-www:/var/www/certbot
      - /data/letsencrypt:/etc/letsencrypt
    networks:
      - internal
